baseURL = "http://tech.kiboko.io/"
languageCode = "fr-fr"
DefaultContentLanguage = "fr"
# theme
theme = "kiboko"
# site title
title = "Accueil - Kiboko"
# disable language
disableLanguages = []
# google analytics
googleAnalytics = "" # paste your analytics ID here. (Ex: UA-123-45)

[[menu.main]]
name = "Contactez-nous"
url = "http://kiboko.fr/fr/contactez-nous/"
weight = 1

[[menu.main]]
name = "Kibokasts"
url = "/kibokasts"
weight = 2

[params]
logo = "images/logo.png"
logo_white = "images/logo.png"
primary_color = "#22014f"
light_color = "#fe8507"
dark_color = "#22014f"
body_color = "#ddd"
text_color = "#666"
text_color_dark = "#333"
white_color = "#eee"
font_family = "lato"

################################ French Language ######################
[Languages.fr]
languageName = "Français"
languageCode = "fr-fr"
weight = 1
home = "Accueil"
copyright = "Thème Hugo Dot personnalisé © [gethugothemes](https://gethugothemes.com/) 2020."

# banner
[Languages.fr.params.banner]
title = "Documentation Kiboko"
subtitle = "Parcourez la documentation pour apprendre à utiliser nos méthodes de travail"
placeholder = "Rechercher une documentation"

# call to action
[Languages.fr.params.cta]
enable = true
title = "Vous n'avez pas trouvé une réponse ?"

# call to action button
[Languages.fr.params.cta.button]
enable = true
label = "Contactez-nous"
link = "http://kiboko.fr/fr/contactez-nous/"
