baseURL = "http://example.org/"
languageCode = "fr-fr"
DefaultContentLanguage = "fr"
# theme
theme = "kiboko"
# site title
title = "Kiboko"
# disable language
disableLanguages = []
# google analytics
googleAnalytics = "" # paste your analytics ID here. (Ex: UA-123-45)

[[menu.main]]
name = "Kibokasts"
url = "/kibokasts"
weight = 1

[params]
logo = "media/logo.png"
logo_white = "media/logo.png"
primary_color = "#22014f"
light_color = "#fe8507"
dark_color = "#22014f"
body_color = "#ddd"
text_color = "#666"
text_color_dark = "#333"
white_color = "#eee"
font_family = "lato"

################################ French Language ######################
[Languages.fr]
languageName = "Français"
languageCode = "fr-fr"
weight = 1
home = "Accueil"
copyright = "The Hugo Documents are copyright © [gethugothemes](https://gethugothemes.com/) 2020."

# banner
[Languages.fr.params.banner]
title = "Documentation Kiboko"
subtitle = "Browse the documentation and knowledge base to start quickly with Middleware"
placeholder = "Have a question? Just ask here or enter terms"

# call to action
[Languages.fr.params.cta]
enable = true
title = "Didn't find an answer to your question?"
content = "Musce libero nunc, dignissim quis turpis quis, semper vehicula dolor. Suspendisse tincidunt consequat quam."

# call to action button
[Languages.fr.params.cta.button]
enable = true
label = "contact us"
link = "contact"
